services:
  #PHP Service
  docker_in_codespace:
    build:
      args:
        user: iqho
        uid: 1000
      context: .
      dockerfile: .docker/Dockerfile
    image: docker_in_codespace
    container_name: docker_in_codespace
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - docker_in_codespace_network

  #MySQL Service
  docker_in_codespace_db:
    image: mysql:8.0
    container_name: docker_in_codespace_db
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-docker_in_codespace}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-docker_in_codespace}
      MYSQL_PASSWORD: ${DB_PASSWORD:-docker_in_codespace}
      MYSQL_USER: ${DB_USERNAME:-docker_in_codespace}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - docker_in_codespace_mysql_data:/var/lib/mysql
    networks:
      - docker_in_codespace_network

  #Nginx Service
  docker_in_codespace_nginx:
    image: nginx:alpine
    container_name: docker_in_codespace_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_APP_PORT}:80"
      - "${DOCKER_APP_SSL_PORT}:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - docker_in_codespace_network
  # phpmyadmin service
  docker_in_codespace_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: docker_in_codespace_phpmyadmin
    depends_on:
      - docker_in_codespace_db
    ports:
      - "${DOCKER_PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: docker_in_codespace_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - docker_in_codespace_network

  docker_in_codespace_redis_cache:
    image: redis:alpine
    restart: always
    container_name: docker_in_codespace_redis_cache
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-docker_in_codespace}
    volumes:
      - docker_in_codespace_cache:/data
    networks:
    - docker_in_codespace_network

#Docker Networks
networks:
  docker_in_codespace_network:
    driver: bridge
    name: docker_in_codespace_network

#Volumes
volumes:
  docker_in_codespace_mysql_data:
  docker_in_codespace_cache:
